### ISSUE TITLE
Feature: Support wildcard searches

### ISSUE THREAD

**Issue by uBadRequest** [nscuro/fdnssearch#12]
Hey nice tool, think you could add a flag for searching for a keyword or supporting regex?

**Comment by uBadRequest** [comment]
`if entryName == domain || strings.HasSuffix(entryName, "."+domain)`

`if entryName == domain || strings.Contains(entryName, domain)`

I just changed this and works for me :+1:

**Comment by nscuro** [comment]
Glad you found a solution that works for you. Note that using `strings.Contains` will yield a lot of false positives though, depending on your target name. 

e.g. searching for `takeaway.com` will then match domains like `bestasiantakeaway.com`, making it hard to stay in scope.

**Comment by uBadRequest** [comment]
Well in my case that wouldn't be a false positive ... that's exactly what I need. There is no scope! I'm looking for trademark violations for the company I work for.
